language: python
python:
    - "3.4"
    - "3.5"
install:
    - "pip install -e ."
    - "pip install -r dev-requirements.txt"
script: "cd demo19 && coverage run --source pagetools manage.py test pagetools main"
after_success:
  coveralls
