dist: xenial
language: python
python:
    - "3.5"
    - "3.6"
install:
    - "pip install -e . "
    - "pip install -r dev_requirements.txt"

script: "coverage run --include='pagetools/*','demo/*' setup.py test"
after_success:
  coveralls
