dist: focal
language: python
python:
    - "3.8"
    - "3.10"
install:
    - "pip install -e . "
    - "pip install -r dev_requirements.txt"

script: "coverage run --include='pagetools/*','demo/*' setup.py test"
after_success:
  coveralls
