# Generated by Django 4.2.17 on 2025-02-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0008_auto_20190530_1343"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuentry",
            name="slug",
        ),
    ]
