# Generated by Django 3.2 on 2022-06-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_auto_20161026_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageTypeDescription',
        ),
    ]
