# Generated by Django 4.2.3 on 2023-11-27 20:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("widgets", "0004_delete_pagetypedescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentwidget",
            name="content",
            field=tinymce.models.HTMLField(verbose_name="Content"),
        ),
    ]
