# Generated by Django 4.2.17 on 2025-02-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0005_alter_contentwidget_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="templatetagwidget",
            options={"verbose_name": "Auto generated widget", "verbose_name_plural": "Auto generated widgets"},
        ),
    ]
