# Generated by Django 4.2.16 on 2024-11-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChoosableTemplateWidget",
        ),
    ]
