name: Pagetools CI on: [push] jobs: build: runs-on: ubuntu-22.04 strategy: max-parallel: 4
      matrix:
        python-version: ["3.11.10", "3.12.7"]
    env:
      RUNNER_TOOL_CACHE: /toolcache
    steps:
    - uses: actions/checkout@v4
    - name: update
      run: apt update
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
        version: 1.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        # cache: 'pip'
        # key: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pdm
        python -m pdm install --prod
        python -m pdm add -dG build
      env:
        AGENT_TOOLSDIRECTORY: /opt/hostedtoolache
    - name: Run Unit-Tests
      run: |
        pdm run python runtests.py
    - uses: actions/setup-node@v4
    - name: Run E2E-Tests
      run: | 
        #  apt update
        #  apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
        npm i --save-dev
        npm run test
